"""
05_robustness_aggregator.py — Day 17

Pulls together the baseline metrics and all three stress test results into
one comparison table, and writes/overwrites the auto-generated section of
ROBUSTNESS_REPORT.md. The hand-written 5-sentence honest reflection at the
top of that file is preserved — only the "## Results" section below it is
regenerated, so re-running this script after re-running 02-04 doesn't wipe
your own analysis.
"""

import json

import config

REPORT_PATH = config.DAY17_DIR / "ROBUSTNESS_REPORT.md"
RESULTS_MARKER = "## Results"


def load_json(path):
    with open(path) as f:
        return json.load(f)


def build_results_section() -> str:
    baseline = load_json(config.BASELINE_METRICS_PATH)
    shift = load_json(config.DISTRIBUTION_SHIFT_RESULTS_PATH)
    noise = load_json(config.NOISE_RESULTS_PATH)
    corruption = load_json(config.CORRUPTION_RESULTS_PATH)

    lines = [RESULTS_MARKER, ""]
    lines.append(
        f"_Auto-generated by `05_robustness_aggregator.py`. "
        f"Baseline test RMSE: {baseline['rmse']:.2f} "
        f"(95% CI: {baseline['rmse_ci']['ci_lower']:.2f} – "
        f"{baseline['rmse_ci']['ci_upper']:.2f}), n_test={baseline['n_test']}._"
    )
    lines.append("")
    lines.append("| Stress Test | Condition | RMSE | RMSLE | n | Δ RMSE vs baseline |")
    lines.append("|---|---|---|---|---|---|")
    lines.append(
        f"| Baseline | clean | {baseline['rmse']:.2f} | {baseline['rmsle']:.4f} | "
        f"{baseline['n_test']} | — |"
    )

    overall_shift = shift["overall"]
    old_shift = shift["old_homes"]
    new_shift = shift["new_homes"]
    lines.append(
        f"| Distribution shift | all test rows | {overall_shift['rmse']:.2f} | "
        f"{overall_shift['rmsle']:.4f} | {overall_shift['n']} | "
        f"{overall_shift['rmse'] - baseline['rmse']:+.2f} |"
    )
    if old_shift:
        lines.append(
            f"| Distribution shift | old homes (< {shift['threshold_year']}) | "
            f"{old_shift['rmse']:.2f} | {old_shift['rmsle']:.4f} | {old_shift['n']} | "
            f"{old_shift['rmse'] - baseline['rmse']:+.2f} |"
        )
    if new_shift:
        lines.append(
            f"| Distribution shift | new homes (>= {shift['threshold_year']}) | "
            f"{new_shift['rmse']:.2f} | {new_shift['rmsle']:.4f} | {new_shift['n']} | "
            f"{new_shift['rmse'] - baseline['rmse']:+.2f} |"
        )

    lines.append(
        f"| Feature noise ({noise['noise_level']*100:.0f}%) | clean | "
        f"{noise['clean']['rmse']:.2f} | {noise['clean']['rmsle']:.4f} | "
        f"{baseline['n_test']} | — |"
    )
    lines.append(
        f"| Feature noise ({noise['noise_level']*100:.0f}%) | noisy | "
        f"{noise['noisy']['rmse']:.2f} | {noise['noisy']['rmsle']:.4f} | "
        f"{baseline['n_test']} | "
        f"{noise['noisy']['rmse'] - noise['clean']['rmse']:+.2f} "
        f"({noise['rmse_degradation_pct']:+.1f}%) |"
    )

    lines.append(
        f"| Label corruption ({corruption['corruption_fraction']*100:.0f}%) | clean labels | "
        f"{corruption['clean_labels']['rmse']:.2f} | "
        f"{corruption['clean_labels']['rmsle']:.4f} | {baseline['n_test']} | — |"
    )
    lines.append(
        f"| Label corruption ({corruption['corruption_fraction']*100:.0f}%) | corrupted labels | "
        f"{corruption['corrupted_labels']['rmse']:.2f} | "
        f"{corruption['corrupted_labels']['rmsle']:.4f} | {baseline['n_test']} | "
        f"{corruption['corrupted_labels']['rmse'] - corruption['clean_labels']['rmse']:+.2f} "
        f"({corruption['rmse_degradation_pct']:+.1f}%) |"
    )
    lines.append("")
    return "\n".join(lines)


def main():
    results_section = build_results_section()

    if REPORT_PATH.exists():
        existing = REPORT_PATH.read_text()
        if RESULTS_MARKER in existing:
            preserved = existing.split(RESULTS_MARKER)[0].rstrip() + "\n\n"
        else:
            preserved = existing.rstrip() + "\n\n"
    else:
        preserved = (
            "# Robustness Report — Day 17\n\n"
            "## 5-Sentence Honest Reflection\n\n"
            "_(Write this by hand after reviewing the table below. "
            "Cover: which test degraded performance most, whether that "
            "matches intuition, and what it implies about deploying this "
            "model on data unlike Ames, IA.)_\n\n"
        )

    REPORT_PATH.write_text(preserved + results_section)
    print(f"Wrote {REPORT_PATH}")


if __name__ == "__main__":
    main()
