"""
config.py — Day 17: Model Card + Robustness Stress Test

Single source of truth for paths, the rebuilt "best model" definition,
and the exact stress-test parameters specified by the roadmap
(20% feature noise, 10% label corruption, one distribution-shift slice).

IMPORTANT — scope correction made before writing this file:
Day 15's actual config.py shows NUMERIC_FEATURES/CATEGORICAL_FEATURES as the
*raw* Ames columns only. Day 14's engineered features (TotalSF, Age, HasPool,
etc.) were never folded into Day 15's pipeline. Day 17 rebuilds Day 15 exactly
as it stands — raw features only. day-14/ is therefore NOT imported here.
That gap is documented as a known limitation in MODEL_CARD.md instead of
silently "fixed."

Assumes this file lives at: <repo_root>/day-17/config.py
and that day-15/ is a sibling directory at the repo root.
"""

from pathlib import Path

# ---------------------------------------------------------------------------
# Repo layout
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parents[1]  # repo root
DAY15_DIR = BASE_DIR / "day-15"
DAY17_DIR = BASE_DIR / "day-17"

# ---------------------------------------------------------------------------
# Data — reuse Day 15's own copy of the dataset, not Day 14's.
# ---------------------------------------------------------------------------
AMES_CSV_PATH = DAY15_DIR / "data" / "AmesHousing.csv"
TARGET_COL = "SalePrice"
DROP_COLS = ["Order", "PID"]  # row identifiers — same as Day 15

# ---------------------------------------------------------------------------
# Cross-day import target (Day 15's pipeline_factory.py + its own config.py)
# ---------------------------------------------------------------------------
DAY15_CONFIG_PATH = DAY15_DIR / "config.py"
DAY15_PIPELINE_FACTORY_PATH = DAY15_DIR / "pipeline_factory.py"

# ---------------------------------------------------------------------------
# Outputs (gitignored — regenerated by scripts)
# Model artifacts (.joblib) live in models/, separate from metrics/results
# (.json) in outputs/, so binary artifacts don't get tangled with readable
# results when browsing the folder.
# ---------------------------------------------------------------------------
OUTPUT_DIR = DAY17_DIR / "outputs"
MODELS_DIR = DAY17_DIR / "models"

BEST_PIPELINE_PATH = MODELS_DIR / "best_pipeline.joblib"
TEST_SPLIT_PATH = MODELS_DIR / "test_split.joblib"

BEST_PARAMS_PATH = OUTPUT_DIR / "best_params.json"
BASELINE_METRICS_PATH = OUTPUT_DIR / "baseline_metrics.json"
DISTRIBUTION_SHIFT_RESULTS_PATH = OUTPUT_DIR / "distribution_shift_results.json"
NOISE_RESULTS_PATH = OUTPUT_DIR / "noise_injection_results.json"
CORRUPTION_RESULTS_PATH = OUTPUT_DIR / "label_corruption_results.json"

# ---------------------------------------------------------------------------
# Reproducibility / split — same as Day 15
# ---------------------------------------------------------------------------
RANDOM_STATE = 42
TEST_SIZE = 0.20

# ---------------------------------------------------------------------------
# Grid search — Day 15's exact grid (2 learning rates x 3 max_depth x
# 2 n_estimators = 12 combos x 5 folds = 60 fits). Rediscovered here since
# the winning combo was never persisted on Day 15.
# ---------------------------------------------------------------------------
CV_FOLDS = 5
SCORING = "neg_root_mean_squared_error"
PARAM_GRID = {
    "model__n_estimators": [100, 300],
    "model__max_depth": [3, 4, 6],
    "model__learning_rate": [0.05, 0.10],
}

# ---------------------------------------------------------------------------
# Stress test parameters — exact single levels per the Day 17 spec
# (not sweeps — that style belongs to Day 12's imbalance study).
# ---------------------------------------------------------------------------
FEATURE_NOISE_LEVEL = 0.20  # 20% noise added to numeric test features
LABEL_CORRUPTION_FRACTION = 0.10  # 10% of test labels shuffled

# Distribution-shift slice: split the held-out test set itself by build era.
# Leakage-free (test rows were never trained on either way); asks whether
# the model performs worse on older homes than newer ones within the same
# held-out set.
SHIFT_COLUMN = "Year Built"
SHIFT_YEAR_THRESHOLD = 1960  # "old" = built before 1960, "new" = 1960+

# ---------------------------------------------------------------------------
# Bootstrap CI for baseline evaluation metrics (Model Card requirement)
# ---------------------------------------------------------------------------
BOOTSTRAP_ITERATIONS = 1000
CI_LOWER_PCT = 2.5
CI_UPPER_PCT = 97.5
